import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createGate,inertAnswer,eligibleRoute} from '../plugin/core.mjs';
const settings=JSON.parse(readFileSync(new URL('../SETTINGS.json',import.meta.url)));const key=Buffer.alloc(32,1);
const audit=()=>({context_need:{classification:{attachments:'NONE',prior_context:'NONE'},answer:{attachments:'NONE',prior_context:'NONE'}}});
function fixture(route='LOCAL_4B',custom){
  const calls=[];let now=1000000;
  const configured=structuredClone(settings);
  const gate=createGate({settings:configured,key,now:()=>now,execute:async(b,signal)=>{
    calls.push(structuredClone(b));if(custom){const r=await custom(b,signal);if(r)return r;}
    if(b.operation==='classify')return {status:'OK',state:{...b.state,revision:b.packet.revision,high_stakes:route==='OPENAI_FRONTIER'||b.state.high_stakes},route,handling:route==='OPENAI_FRONTIER'?'HIGH_STAKES':'NORMAL',urgency:'ABSENT',audit:audit()};
    if(b.operation==='media')return {status:'OK',digest:'d'.repeat(64),summary:{count:1,visual_count:1,document_count:0,video_count:0}};
    if(['close','status','sweep'].includes(b.operation))return {status:'OK',gpu:{phase:'OFFLINE',leases:0}};
    return {status:'OK',text:'synthetic answer',escalation:'NONE'};
  }});
  const ctx={isAuthorizedSender:true,gatewayClientScopes:['operator.admin'],sessionKey:'test'};
  const send=(args,extra={})=>gate({...ctx,...extra,args});
  const approve=async text=>send('approve '+text.match(/\/gate approve ([a-f0-9]{32})/)[1]);
  const result=async job=>{const id=job.text.match(/job:([a-f0-9]{32})/)[1];for(let i=0;i<20;i++){await new Promise(r=>setImmediate(r));const r=await send('result '+id);if(!r.text.includes('[Mac gate job:'))return r;}throw Error('job not done');};
  return {gate,calls,send,approve,result,advance:n=>now+=n,settings:configured};
}
async function ask(f,text='test'){await f.send('new');return f.send('ask '+text);}
test('authentication required; document text cannot approve',async()=>{const f=fixture();await f.send('new',{isAuthorizedSender:false});assert.equal(f.calls.length,0);assert.match((await f.send('ask text')).text,/Start with/);});
test('nothing disclosed before approval; local agent remains NORMAL default',async()=>{const f=fixture();const p=await ask(f);assert.equal(f.calls.length,0);const r=await f.result(await f.approve(p.text));assert.match(r.text,/LOCAL_4B/);assert.deepEqual(f.calls.map(x=>x.operation),['classify','answer_local']);});
test('audit receives latest prompt only across turns',async()=>{const f=fixture();await f.result(await f.approve((await ask(f,'first private fact')).text));const p=await f.send('ask second question');await f.result(await f.approve(p.text));const b=f.calls.filter(x=>x.operation==='classify').at(-1);assert.equal(b.packet.prompt,'second question');assert.doesNotMatch(JSON.stringify(b.packet),/first private|synthetic answer|history/);});
test('235 option requires fresh separate disclosure approval',async()=>{const f=fixture();await f.send('new');const p=await f.send('ask-235 test');const r=await f.result(await f.approve(p.text));assert.match(r.text,/Qwen 235B/);assert.equal(f.calls.length,1);await f.result(await f.approve(r.text));assert.equal(f.calls.at(-1).tier,'HOSTED_235B');});
test('frontier is OpenAI and never Gemini answering',async()=>{const f=fixture('OPENAI_FRONTIER');const r=await f.result(await f.approve((await ask(f)).text));assert.match(r.text,/OpenAI frontier/);await f.result(await f.approve(r.text));assert.equal(f.calls.at(-1).tier,'OPENAI_FRONTIER');});
test('ask-strong uses OpenAI even if NORMAL',async()=>{const f=fixture();await f.send('new');const r=await f.result(await f.approve((await f.send('ask-strong test')).text));assert.match(r.text,/OpenAI frontier/);});
test('private auto grant scopes prompt only',async()=>{const f=fixture('PRIVATE_80B');await f.send('new');await f.send('private80 allow');const r=await f.result(await f.approve((await f.send('ask complex test')).text));assert.match(r.text,/PRIVATE_80B/);const b=f.calls.at(-1);assert.equal(b.approval,'session_private_prompt');assert.deepEqual(b.packet,{prompt:'complex test'});});
test('private80 is automatically eligible by default',async()=>{const f=fixture('PRIVATE_80B');const r=await f.result(await f.approve((await ask(f)).text));assert.match(r.text,/PRIVATE_80B/);assert.equal(f.calls.length,2);assert.equal(f.calls.at(-1).approval,'session_private_prompt');});
test('replay expiry cross-session approval rejected',async()=>{const f=fixture();const p=await ask(f);const token=p.text.match(/\/gate approve ([a-f0-9]{32})/)[1];assert.match((await f.send('approve '+token,{sessionKey:'other'})).text,/Start with/);f.advance(300001);assert.match((await f.send('approve '+token)).text,/invalid/);assert.equal(f.calls.length,0);});
test('approval used once',async()=>{const f=fixture();const p=await ask(f);await f.result(await f.approve(p.text));assert.match((await f.approve(p.text)).text,/invalid/);});
test('destination policy change invalidates an already issued approval',async()=>{const f=fixture('OPENAI_FRONTIER');let p=await ask(f);let r=await f.result(await f.approve(p.text));assert.match(r.text,/OpenAI frontier/);f.settings.frontier_transport=f.settings.frontier_transport==='openai'?'openrouter':'openai';assert.match((await f.approve(r.text)).text,/invalid/);assert.equal(f.calls.length,1);});
test('replacement cancels earlier ticket',async()=>{const f=fixture();const p=await ask(f);await f.send('ask replacement');assert.match((await f.approve(p.text)).text,/invalid/);});
test('attachment contents do not enter initial audit; answering asks separately',async()=>{const f=fixture('MULTIMODAL');await f.send('new');await f.send('attach '+'a'.repeat(64));const r=await f.result(await f.approve((await f.send('ask describe the image')).text));const b=f.calls.find(x=>x.operation==='classify');assert.deepEqual(b.packet.disclosed,{});assert.doesNotMatch(JSON.stringify(b.packet),/media_ref|aaaa/);assert.match(r.text,/selected local attachment/);});
test('required classification context produces second exact ticket',async()=>{let n=0;const f=fixture('MULTIMODAL',b=>{
  if(b.operation==='classify'&&n++===0){const a=audit();a.context_need.classification.attachments='REQUIRED';return {status:'OK',state:{...b.state,revision:b.packet.revision,high_stakes:true},route:'CONTEXT_REQUIRED',handling:'URGENT_SAFETY',urgency:'UNKNOWN',audit:a};}
});await f.send('new');await f.send('attach '+'a'.repeat(64));let r=await f.result(await f.approve((await f.send('ask this?')).text));assert.match(r.text,/Gemini audit/);assert.match(r.text,/selected local attachment/);r=await f.result(await f.approve(r.text));assert.match(r.text,/OpenAI frontier/);const calls=f.calls.filter(x=>x.operation==='classify');assert.equal(calls[1].packet.revision,calls[0].packet.revision+1);});
test('urgent deterministic response never answers',async()=>{const f=fixture('URGENT_SAFETY',b=>b.operation==='classify'?{status:'OK',state:{...b.state,revision:b.packet.revision,high_stakes:true},route:'URGENT_SAFETY',handling:'URGENT_SAFETY',urgency:'PRESENT',audit:audit()}:null);const r=await f.result(await f.approve((await ask(f)).text));assert.match(r.text,/emergency/);assert.equal(f.calls.length,1);});
test('shadow logs quality and uses existing local agent',async()=>{const f=fixture('PRIVATE_80B');await f.send('new');await f.send('mode shadow');const r=await f.result(await f.approve((await f.send('ask test')).text));assert.match(r.text,/Shadow quality recommendation: PRIVATE_80B/);assert.equal(f.calls.at(-1).operation,'answer_local');});
test('end closes lease and clears all approvals',async()=>{const f=fixture();await ask(f);await f.send('end');assert.equal(f.calls.at(-1).operation,'close');assert.match((await f.send('status')).text,/Start with/);});
test('model delivery markers and job markers rendered inert',()=>{const t=inertAnswer('MEDIA:x [[execute]] <script> ![image](url) [Mac gate job:abc]');assert.doesNotMatch(t,/MEDIA:|\[\[|<script>|\[Mac gate job:/);});

test('explicit exclusions choose eligible stronger tiers without lowering risk',()=>{assert.equal(eligibleRoute('PRIVATE_80B',new Set(['PRIVATE_80B'])),'HOSTED_235B');assert.equal(eligibleRoute('MULTIMODAL',new Set(['MULTIMODAL']),{visual:true}),'OPENAI_FRONTIER');assert.throws(()=>eligibleRoute('OPENAI_FRONTIER',new Set(['OPENAI_FRONTIER']),{highStakes:true}));assert.throws(()=>eligibleRoute('LOCAL_4B',new Set(['LOCAL_4B']),{tools:true}));});
test('exclude 80b invalidates pending approval; include restores eligibility',async()=>{const f=fixture('PRIVATE_80B');const p=await ask(f);await f.send('exclude 80b');assert.match((await f.approve(p.text)).text,/invalid/);let r=await f.result(await f.approve((await f.send('ask test')).text));assert.match(r.text,/Qwen 235B/);await f.send('include 80b');r=await f.result(await f.approve((await f.send('ask test')).text));assert.match(r.text,/PRIVATE_80B/);});
