[install]
is_configured = 0

[ui]
is_visible = 1
label = Sanctum Restricted Content

[launcher]
author = Sanctum
description = Restricted interaction and quality telemetry searches for Splunk Enterprise.
version = 1.0.0

[package]
id = sanctum_content

