const str=(max=200)=>({type:'string',minLength:1,maxLength:max});
const obj=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
const enumeration=(...values)=>({type:'string',enum:values});
export const utilityTools=[
 {name:'calc',description:'Calculate exact arithmetic, percentages, powers and parentheses locally. Supports abs, sqrt, min, max, round, floor, ceil.',parameters:obj({expression:str(512)},['expression'])},
 {name:'date_math',description:'Compute dates, day differences, weekdays or timezone conversion locally. ISO dates; today/tomorrow/yesterday use timezone (default UTC). Conversion requires an offset.',parameters:{...obj({operation:enumeration('now','add','between','weekday','resolve','convert_timezone'),date:str(80),other:str(80),amount:{type:'integer',minimum:-10000,maximum:10000},unit:enumeration('days','weeks','months'),timezone:str(80),reference:str(80)},['operation']),allOf:[{if:{properties:{operation:{const:'add'}}},then:{required:['date','amount']}},{if:{properties:{operation:{const:'between'}}},then:{required:['date','other']}},{if:{properties:{operation:{enum:['weekday','resolve','convert_timezone']}}},then:{required:['date']}}]}},
 {name:'unit_convert',description:'Convert distance, mass, temperature, volume, area, speed, storage, time and SI engineering units locally. Use C/F/K, mi/km, GiB/GB; gallon needs US_gallon or imperial_gallon.',parameters:obj({value:{type:'number'},from_unit:str(40),to_unit:str(40)},['value','from_unit','to_unit'])},
 {name:'structured_parse',description:'Validate/parse JSON, URL, CSV/TSV, extract a JSON dotted path, or match a fixed-width regex locally. No files, network or executable code.',parameters:{...obj({format:enumeration('json','url','csv','tsv','extract','regex'),text:str(32768),path:str(256),pattern:str(128),headers:{type:'boolean'}},['format','text']),allOf:[{if:{properties:{format:{const:'extract'}}},then:{required:['path']}},{if:{properties:{format:{const:'regex'}}},then:{required:['pattern']}},{if:{properties:{format:{enum:['json','url','csv','tsv','extract']}}},then:{not:{required:['pattern']}}}]}}
];
